version: '3.5'

services:
  api:
    container_name: text-reminder-api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: text-reminder-api:latest
    env_file: ./api/.env
    environment:
      - VIRTUAL_HOST=api.textreminder.io
    volumes:
      - api_db_data:/data

  client:
    container_name: text-reminder-client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: text-reminder-client:latest
    env_file: ./client/.env

  redis-server:
    container_name: text-reminder-redis
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - redis_db_data:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  nginx-proxy:
    container_name: text-reminder-proxy
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 1337:1337

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    env_file: ./api/.env
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  redis_db_data:
    external: true
  api_db_data:
    external: true
  conf:
  vhost:
  html:
  dhparam:
  certs:
