name: unit-test-client

on: [push]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install deps
      working-directory: ./client
      run: npm ci
    - name: Run unit tests
      working-directory: ./client
      run: npm run test:unit
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}